name: starsearch_fixed
description: "AI-based Fruit Classification"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  permission_handler: ^11.0.1
  path_provider: ^2.1.2
  image_picker: ^1.0.4
  external_path: ^2.2.0
  camera: ^0.10.5+2
  share_plus: ^7.2.2
  flutter_local_notifications: ^19.0.0
  flutter_bloc: ^9.1.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  dio: ^5.4.0
  url_launcher: ^6.2.5
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png" # 🧠 Update this path if you have a custom app icon

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoCondensed-Italic.ttf
          style: italic
